import os
import requests
import logging
import json
from datetime import datetime, timedelta, timezone, date, time

BASE_URL_SAMPLE_DATA = "https://api.openweathermap.org/data/2.5/weather"
BASE_URL_HISTORICAL_DATA = "https://api.openweathermap.org/data/2.5/onecall/timemachine"
API_KEY = os.getenv("API_KEY")

logging.basicConfig(level=logging.INFO)


def get_data_from_api(url: str, params: dict):
    return requests.get(url, params=params).json()


def write_file(content, path_file: str) -> None:
    with open(path_file, 'w') as f:
        f.write(content)


def get_five_days_ago_unix_time():
    five_days_ago = date.today() - timedelta(days=5)

    five_days_ago_unix_time = int(datetime.combine(
        five_days_ago, time(0, 0, 0), tzinfo=timezone.utc).timestamp())

    return five_days_ago_unix_time


def get_cities_weather_data(cities, five_days_ago: int):
    cities_with_weather_data = []

    for city, coord in cities.items():
        logging.info(f"Getting five days ago weather data of city {city}...")

        params = {
            "lat": coord["lat"],
            "lon": coord["lon"],
            "dt": five_days_ago,
            "appid": API_KEY
        }

        response = get_data_from_api(BASE_URL_HISTORICAL_DATA, params)
        cities_with_weather_data.append({city: response})

        logging.info(
            f"Five days ago weather data successfully recovered of city {city}!")

    logging.info(
        f"All weather data values for cities listed above were recovered.")

    return cities_with_weather_data


def get_cities_lat_long(cities: list):
    cities_with_lat_lon = {}

    for city in cities:
        logging.info(f"Getting latitude and longitude of city {city}...")

        params = {
            "q": city,
            "appid": API_KEY
        }

        response = get_data_from_api(BASE_URL_SAMPLE_DATA, params)

        city_lat_long = response["coord"]
        cities_with_lat_lon.update({city: city_lat_long})

        logging.info(
            f"Latitude and longitude successfully recovered of city {city}!")

    logging.info(f"All latitude and longitude values were recovered.")

    return cities_with_lat_lon


def process_file(file: str, dir: str, source: str, data, five_days_ago: int = None):
    functions = {
        "sample": get_cities_lat_long(data),
        "weather": get_cities_weather_data(data, five_days_ago)
    }

    if file in os.listdir(dir):
        extracted_data = json.load(open(f"{dir}/{file}"))
    else:
        extracted_data = functions[source]

        write_file(extracted_data, dir, file)

    return extracted_data


def _main():
    cities = [
        "Shenzhen", "Fez", "Rio De Janeiro", "Taipei", "São Paulo", "Isfahan", "Warsaw",
        "Bengaluru", "Dar es Salaam", "Nagpur"
    ]  # list generated by https://www.randomlists.com/random-world-cities?dup=false&qty=10

    five_days_ago = get_five_days_ago_unix_time()
    sample_file = "cities-lat-long.json"
    weather_data_file = f"{base_weather_data_file}_{five_days_ago}"
    base_weather_data_file = "cities-weather-data"
    raw_dir = "data/01_raw"
    refined_dir = "data/02_refined"

    cities_with_lat_lon = process_file(sample_file, raw_dir, "sample", cities)

    historical_weather = process_file(
        weather_data_file, refined_dir, "weather", cities_with_lat_lon)


if __name__ == '__main__':
    _main()
